theme: jekyll-theme-architect
baseurl: ""
excerpt_separator: "<!--more-->"
permalink: /blog/:title/
title: LazyDom
description: Security, automation, and tech guides by LazyDom.
github:
  repository_url: https://github.com/LazyDom/blog
  owner_url: https://github.com/LazyDom
  owner_name: LazyDom
  is_project_page: true
