theme: jekyll-theme-architect
baseurl: ""
excerpt_separator: "<!--more-->"
permalink: /blog/:title/
title: LazyDom
description: Personal site of LazyDom - DevSecOps engineer, security evangelist, blogger, and automation enthusiast. Explore my bio, portfolio, blog, and more.
github:
  repository_url: https://github.com/LazyDom/blog
  owner_url: https://github.com/LazyDom
  owner_name: LazyDom
  is_project_page: true
blog_name: LazyDom's Blog
plugins:
  - jemoji