# GitHub Actions Workflow: Lint, URL Check, Build, and Deploy Jekyll Blog

name: Lint, URL Check, Build & Deploy Jekyll Blog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint-and-linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check GitHub links only (lychee-action)
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: >-
            --verbose
            --no-progress
            --exclude-path 'node_modules' --exclude-path '_site' --exclude-path '.git'
            --include 'github.com'
            './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check non-GitHub links with concurrency limit (lychee-action)
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: >-
            --verbose
            --no-progress
            --exclude-path 'node_modules' --exclude-path '_site' --exclude-path '.git'
            --exclude 'github.com' --max-concurrency 2
            './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files (including Jekyll front matter)
        run: |
          yamllint . --format colored --strict

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint-and-linkcheck
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Check GitHub links in built site (lychee-action)
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: >-
            --verbose
            --no-progress
            --include 'github.com'
            './_site/**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check non-GitHub links in built site (lychee-action)
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: >-
            --verbose
            --no-progress
            --exclude 'github.com' --max-concurrency 2
            './_site/**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
