name: Jekyll Lint Build URL Check Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint . --format colored --strict

  build:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll (GitHub Pages)
        uses: actions/jekyll-build-pages@v1.0.13
        env:
          JEKYLL_ENV: production
          PAGES_REPO_NWO: ${{ github.repository }}
      - name: Generate dynamic lychee ignore
        run: bash scripts/generate_lychee_ignore.sh
      - name: Debug lycheeignore presence (pre-checks)
        run: |
          echo "PWD=$(pwd)"; ls -al . | sed 's/^/  /'
          if [ -f .lycheeignore ]; then echo '--- .lycheeignore (head) ---'; sed -n '1,60p' .lycheeignore; else echo 'MISSING .lycheeignore'; fi
      - name: Check GitHub links with lychee-action
        uses: lycheeverse/lychee-action@v2.6.1
        with:
          args: >-
            --verbose
            --no-progress
            --include github.com
            './_site/**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check non-GitHub links with lychee-action
        uses: lycheeverse/lychee-action@v2.6.1
        with:
          args: >-
            --verbose
            --no-progress
            --exclude github.com --exclude x.com --exclude raspberrypi.com --exclude abuseipdb.com --max-concurrency 2
            --exclude-file .lycheeignore
            './_site/**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ensure lycheeignore exists (fallback)
        if: always()
        run: |
          if [ ! -f .lycheeignore ]; then echo '# added: $(date -u +%Y-%m-%d)' > .lycheeignore; fi
          echo 'Final .lycheeignore size:'; wc -l .lycheeignore || true
      - name: Upload lychee ignore file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-ignore-${{ github.run_id }}
          path: ${{ github.workspace }}/.lycheeignore
          include-hidden-files: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
