# Link Check Only
# This workflow runs lychee link checking on the built Jekyll site only.
# See: https://github.com/lycheeverse/lychee-action

name: Links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Check GitHub links in built site (lychee-action)
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          output: lychee-github-links-output.json
          args: >-
            --verbose
            --no-progress
            --include 'github.com'
            --exclude '/blog/'
            --exclude '/assets/'
            --exclude '/images/'
            './_site/**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload GitHub links lychee output
        uses: actions/upload-artifact@v4
        with:
          name: lychee-github-links-output
          path: lychee-github-links-output.json

      - name: Check non-GitHub links in built site (lychee-action)
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          output: lychee-non-github-links-output.json
          args: >-
            --verbose
            --no-progress
            --exclude 'github.com' --max-concurrency 2
            --exclude '/blog/'
            --exclude '/assets/'
            --exclude '/images/'
            './_site/**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload non-GitHub links lychee output
        uses: actions/upload-artifact@v4
        with:
          name: lychee-non-github-links-output
          path: lychee-non-github-links-output.json
