# Link Check Only
# This workflow builds the Jekyll site and runs lychee link checking on the built output.
# See: https://github.com/lycheeverse/lychee-action

name: Links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages-linkcheck"
  cancel-in-progress: false

jobs:
  build-linkcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll (GitHub Pages)
        uses: actions/jekyll-build-pages@v1.0.13
      - name: Check GitHub links with lychee-action
        uses: lycheeverse/lychee-action@v2.5.0
        with:
          args: >-
            --verbose
            --no-progress
            --include github.com
            './_site/**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check non-GitHub links with lychee-action
        uses: lycheeverse/lychee-action@v2.5.0
        with:
          args: >-
            --verbose
            --no-progress
            --exclude github.com --exclude x.com --exclude raspberrypi.com --exclude abuseipdb.com --exclude 'https://lazydom.xyz/blog/email-security-phishing-analysis/' --max-concurrency 2
            './_site/**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
